// ⚠️ AUTO-GENERATED FILE — nie edytuj ręcznie. Edytuj scripts/generateRegistry.js

import Article100tysiecyludzinamosciewsydneyogromnyprotestwsprawiegazy from "@/articles/Article100tysiecyludzinamosciewsydneyogromnyprotestwsprawiegazy";
import Article15sierpniaajedzeniemiesarozwiewamywatpliwosci from "@/articles/Article15sierpniaajedzeniemiesarozwiewamywatpliwosci";
import Article65miliardadolarowzaczogizkoreiczypolskazbroisienapowaznie from "@/articles/Article65miliardadolarowzaczogizkoreiczypolskazbroisienapowaznie";
import Article6dnipodlupadrogowkiruszyaogolnoeuropejskaakcjaroadpol from "@/articles/Article6dnipodlupadrogowkiruszyaogolnoeuropejskaakcjaroadpol";
import Article800tylkodlawybranychwyciekpropozycjireformyoburzyopiniepubliczna from "@/articles/Article800tylkodlawybranychwyciekpropozycjireformyoburzyopiniepubliczna";
import Article80latpohiroszimieswiatznowigrazogniematomu from "@/articles/Article80latpohiroszimieswiatznowigrazogniematomu";
import Articleaiwlodowceinabiurkuprzyszloscwlasniesiezaczela from "@/articles/Articleaiwlodowceinabiurkuprzyszloscwlasniesiezaczela";
import Articlealkoholowaplagaczypolskatracikontrolenadnarodowymnalogiem from "@/articles/Articlealkoholowaplagaczypolskatracikontrolenadnarodowymnalogiem";
import Articleandrzejdudaodebraodznaczeniejolancielangepowodwspopracazsb from "@/articles/Articleandrzejdudaodebraodznaczeniejolancielangepowodwspopracazsb";
import Articleautonomicznataksowkabaiduwpadadowykopuwchongqingupowaznepytaniaobezpieczenstwoai from "@/articles/Articleautonomicznataksowkabaiduwpadadowykopuwchongqingupowaznepytaniaobezpieczenstwoai";
import Articlebronwrekachobywatelicooznaczalawinowywzrostpozwolennabronwpolsce from "@/articles/Articlebronwrekachobywatelicooznaczalawinowywzrostpozwolennabronwpolsce";
import Articlebryanadamszgwiazdawkrakowietumyfanowiwyprzedanykoncert from "@/articles/Articlebryanadamszgwiazdawkrakowietumyfanowiwyprzedanykoncert";
import Articleburzeparalizujapolskeimgwostrzegaawarszawatonie from "@/articles/Articleburzeparalizujapolskeimgwostrzegaawarszawatonie";
import Articlechopinasonatainparispolskasuperprodukcjaolegendziemuzyki from "@/articles/Articlechopinasonatainparispolskasuperprodukcjaolegendziemuzyki";
import Articlecoldplayikorporacyjnaburzakamerauchwyciaceoiszefowahr from "@/articles/Articlecoldplayikorporacyjnaburzakamerauchwyciaceoiszefowahr";
import Articlecorazwiekszezmeczeniewojnanaukrainie from "@/articles/Articlecorazwiekszezmeczeniewojnanaukrainie";
import Articleczydzisjestniedzielahandlowasprawdz31sierpnia2025 from "@/articles/Articleczydzisjestniedzielahandlowasprawdz31sierpnia2025";
import Articleczypolacysagotowinazyciebezalkoholu from "@/articles/Articleczypolacysagotowinazyciebezalkoholu";
import Articledemolkawizbieprzyjecwsosnowcu36latekwtargnadoszpitalaizdewastowawnetrze from "@/articles/Articledemolkawizbieprzyjecwsosnowcu36latekwtargnadoszpitalaizdewastowawnetrze";
import Articledramatwkirgistaniepacjenciumierajaprzezbraklekow from "@/articles/Articledramatwkirgistaniepacjenciumierajaprzezbraklekow";
import Articledziakatonowemieszkaniepolacyzmieniajastylzycianazielony from "@/articles/Articledziakatonowemieszkaniepolacyzmieniajastylzycianazielony";
import Articleeksplozjadronanawschodziepolskirosnacenapieciaprzygranicy from "@/articles/Articleeksplozjadronanawschodziepolskirosnacenapieciaprzygranicy";
import Articlefimendurovintagetrophy2025klasycznemotocyklewracajanaszlakipiekoszowa from "@/articles/Articlefimendurovintagetrophy2025klasycznemotocyklewracajanaszlakipiekoszowa";
import Articlegpt5bezrewolucjiczysztucznainteligencjautknelawmiejscu from "@/articles/Articlegpt5bezrewolucjiczysztucznainteligencjautknelawmiejscu";
import Articlegrozneburzeiupanadpolskaimgwostrzeganiemalpoowekraju from "@/articles/Articlegrozneburzeiupanadpolskaimgwostrzeganiemalpoowekraju";
import Articlehamaspublikujenagraniezakadnikaprzerazajacewideoporuszaswiat from "@/articles/Articlehamaspublikujenagraniezakadnikaprzerazajacewideoporuszaswiat";
import Articleholandiawysylazolnierzyisystempatriotdopolskisolidarnoscnatowpraktyce from "@/articles/Articleholandiawysylazolnierzyisystempatriotdopolskisolidarnoscnatowpraktyce";
import Articleinflacjaspadaalecenywsklepachwciazwysokiegdzietkwiproblem from "@/articles/Articleinflacjaspadaalecenywsklepachwciazwysokiegdzietkwiproblem";
import Articleinpostpodostrzaemrekordowypodatekekspansjawhiszpaniiibuntkurierow from "@/articles/Articleinpostpodostrzaemrekordowypodatekekspansjawhiszpaniiibuntkurierow";
import Articleintelrezygnujezinwestycjiwpolscecodalejzrynkiempoprzewodnikow from "@/articles/Articleintelrezygnujezinwestycjiwpolscecodalejzrynkiempoprzewodnikow";
import Articlejackowskiprzewidujepozarifaleuchodzcowwpolsce from "@/articles/Articlejackowskiprzewidujepozarifaleuchodzcowwpolsce";
import Articlejanurbannowymselekcjoneremreprezentacjipolski from "@/articles/Articlejanurbannowymselekcjoneremreprezentacjipolski";
import Articlejosemnetoperekmezczyznarozebrasienadachurestauracjihelniezapomnitejnocy from "@/articles/Articlejosemnetoperekmezczyznarozebrasienadachurestauracjihelniezapomnitejnocy";
import Articlekatastrofaf16wradomiuairshow2025przerwanepotragicznymwypadku from "@/articles/Articlekatastrofaf16wradomiuairshow2025przerwanepotragicznymwypadku";
import Articlekatowickakwkwieczorekzmieniasiewnowoczesnyhubtechnologiczny from "@/articles/Articlekatowickakwkwieczorekzmieniasiewnowoczesnyhubtechnologiczny";
import Articlekosiniakkamyszwolynwarunkiemakcesjiukrainydoue from "@/articles/Articlekosiniakkamyszwolynwarunkiemakcesjiukrainydoue";
import Articlekosiniakkamyszzelenskipowiniendolaczycdoszczytutrumpputin from "@/articles/Articlekosiniakkamyszzelenskipowiniendolaczycdoszczytutrumpputin";
import Articlekrwawyksiezycjuz7wrzesniajednoznajdluzszychzacmienwostatnichlatach from "@/articles/Articlekrwawyksiezycjuz7wrzesniajednoznajdluzszychzacmienwostatnichlatach";
import Articlelauradahlmeierciezkorannapowypadkuwpakistaniedramatycznaakcjaratunkowawkarakorum from "@/articles/Articlelauradahlmeierciezkorannapowypadkuwpakistaniedramatycznaakcjaratunkowawkarakorum";
import Articlelauradahlmeierniezyjetragicznyfinawyprawywkarakorum from "@/articles/Articlelauradahlmeierniezyjetragicznyfinawyprawywkarakorum";
import Articlemanewryzapad2025ukrainaostrzegaprzedprowokacjami from "@/articles/Articlemanewryzapad2025ukrainaostrzegaprzedprowokacjami";
import Articlemarkcarneywpolscekanadyjskipremierzaciesniastrategicznewiezi from "@/articles/Articlemarkcarneywpolscekanadyjskipremierzaciesniastrategicznewiezi";
import Articlemasowyatakrosjinaukrainepolskawstanieczujnosci from "@/articles/Articlemasowyatakrosjinaukrainepolskawstanieczujnosci";
import Articlemasowystopdrivedlacitroenowkierowcybezautserwisysparalizowane from "@/articles/Articlemasowystopdrivedlacitroenowkierowcybezautserwisysparalizowane";
import Articlemauritiuspodwodaostrzezenieprzedsilnymifalaminawybrzezu from "@/articles/Articlemauritiuspodwodaostrzezenieprzedsilnymifalaminawybrzezu";
import Articlemcdonaldspolskaukaranyrekordowagrzywna4mlnzawyciekdanychpracownikow from "@/articles/Articlemcdonaldspolskaukaranyrekordowagrzywna4mlnzawyciekdanychpracownikow";
import Articlemojpiespijewodezkranuhitczyobciachweterynarzepodzieleni from "@/articles/Articlemojpiespijewodezkranuhitczyobciachweterynarzepodzieleni";
import Articlenowatablicaalimentacyjnaojcieczdwojkadziecizostajezniewielkaczesciapensji from "@/articles/Articlenowatablicaalimentacyjnaojcieczdwojkadziecizostajezniewielkaczesciapensji";
import Articleobowiazkowebadaniapsychologicznedlakierowcowco5latbezpieczenstwoczyprzesada from "@/articles/Articleobowiazkowebadaniapsychologicznedlakierowcowco5latbezpieczenstwoczyprzesada";
import Articleorlensprzedajepolskapresskonieceksperymentuzpanstwowymwlascicielemmediow from "@/articles/Articleorlensprzedajepolskapresskonieceksperymentuzpanstwowymwlascicielemmediow";
import Articleozzyosbourneniezyjelegendarockapozegnaasiezfanami from "@/articles/Articleozzyosbourneniezyjelegendarockapozegnaasiezfanami";
import Articlepacaminimalnaw2026rokurzadujawniapropozycje from "@/articles/Articlepacaminimalnaw2026rokurzadujawniapropozycje";
import Articlepanikanatomorrowlandscenawogniuewakuacjatysiecyosob from "@/articles/Articlepanikanatomorrowlandscenawogniuewakuacjatysiecyosob";
import Articlepierwszakobietakapitanwpolskiejsluzbiesar from "@/articles/Articlepierwszakobietakapitanwpolskiejsluzbiesar";
import Articlepolacyuciekajanaworkationpracazdalnaiurlopwjednym from "@/articles/Articlepolacyuciekajanaworkationpracazdalnaiurlopwjednym";
import Articlepolakzatrzymanynabialorusipodzarzutemszpiegostwa from "@/articles/Articlepolakzatrzymanynabialorusipodzarzutemszpiegostwa";
import Articlepolitycznyklinczprzedzaprzysiezeniemnawrockikontratusk from "@/articles/Articlepolitycznyklinczprzedzaprzysiezeniemnawrockikontratusk";
import Articlepolskajasnostawiagranicewsparciedlaukrainytakalebezpolskichzolnierzy from "@/articles/Articlepolskajasnostawiagranicewsparciedlaukrainytakalebezpolskichzolnierzy";
import Articlepolskakupujerekordoweiloscizlotaswiatowyliderw2025roku from "@/articles/Articlepolskakupujerekordoweiloscizlotaswiatowyliderw2025roku";
import Articlepolskamodernizujeflotef16kontraktwart38mldusd from "@/articles/Articlepolskamodernizujeflotef16kontraktwart38mldusd";
import Articlepolskarozwazaprzywroceniewizdlaukraincowpowrotgranicczykoniecznosc from "@/articles/Articlepolskarozwazaprzywroceniewizdlaukraincowpowrotgranicczykoniecznosc";
import Articlepolskastawianaenergetykewiatrowanabaltykumiliardoweinwestycjeiambitnecele from "@/articles/Articlepolskastawianaenergetykewiatrowanabaltykumiliardoweinwestycjeiambitnecele";
import Articlepolskastawianawlasnyprzemyslamunicji from "@/articles/Articlepolskastawianawlasnyprzemyslamunicji";
import Articlepolskawstrzymaaschengencosiedziejenagranicachzniemcamiilitwa from "@/articles/Articlepolskawstrzymaaschengencosiedziejenagranicachzniemcamiilitwa";
import Articlepolskazbozemstoistabilnezbioryalewyzwaniarosna from "@/articles/Articlepolskazbozemstoistabilnezbioryalewyzwaniarosna";
import Articlepolskazmedalaminaigrzyskachswiatowych2025imponujacydorobekwchinach from "@/articles/Articlepolskazmedalaminaigrzyskachswiatowych2025imponujacydorobekwchinach";
import Articlepolskiastronautasawoszuznanskibezpieczniewrocinaziemie from "@/articles/Articlepolskiastronautasawoszuznanskibezpieczniewrocinaziemie";
import Articlepolskoirlandzkaakcjarozbijaganginarkotykowewarte240mln from "@/articles/Articlepolskoirlandzkaakcjarozbijaganginarkotykowewarte240mln";
import Articleprezydentdudawogniukrytykipowypowiedzionato from "@/articles/Articleprezydentdudawogniukrytykipowypowiedzionato";
import Articleprezydentnawrockizawetowaltrzyustawynajwiekszykryzyslegislacyjnykadencji from "@/articles/Articleprezydentnawrockizawetowaltrzyustawynajwiekszykryzyslegislacyjnykadencji";
import Articleprezydentpodnosiwiekemerytalnypodpiszozony from "@/articles/Articleprezydentpodnosiwiekemerytalnypodpiszozony";
import Articleprezydentpolskizadareparacjiodniemiecwrocznicewybuchuiiwojnyswiatowej from "@/articles/Articleprezydentpolskizadareparacjiodniemiecwrocznicewybuchuiiwojnyswiatowej";
import Articleprokuraturazlecasekcjezwlokstanislawasoyki from "@/articles/Articleprokuraturazlecasekcjezwlokstanislawasoyki";
import Articlerocznicapakturibbentropmolotowostrzezenieprezydentanawrockiego from "@/articles/Articlerocznicapakturibbentropmolotowostrzezenieprezydentanawrockiego";
import Articlerosyjskinalotnakijowofiaryizniszczeniawstolicyukrainy from "@/articles/Articlerosyjskinalotnakijowofiaryizniszczeniawstolicyukrainy";
import Articlerzadkiezjawiskonadbaltykiemazosiemtrabwodnychjednoczesnie from "@/articles/Articlerzadkiezjawiskonadbaltykiemazosiemtrabwodnychjednoczesnie";
import Articlerzadpodnosipodatekdlabankowdodatkowe65mldzlnaobrone from "@/articles/Articlerzadpodnosipodatekdlabankowdodatkowe65mldzlnaobrone";
import Articlerzadrezygnujezpodatkuodrezerwbankowych from "@/articles/Articlerzadrezygnujezpodatkuodrezerwbankowych";
import Articlesensacyjneodkryciewgdanskugrobrycerzapodlodziarnia from "@/articles/Articlesensacyjneodkryciewgdanskugrobrycerzapodlodziarnia";
import Articlesiniceatakujabatykplazezamknietegisbijenaalarm from "@/articles/Articlesiniceatakujabatykplazezamknietegisbijenaalarm";
import Articlesmiercpodczaspolowanianalubelszczyznietragediawlesie from "@/articles/Articlesmiercpodczaspolowanianalubelszczyznietragediawlesie";
import Articlespotkanietrumpputinwanchoragewielkieoczekiwaniabrakprzelomu from "@/articles/Articlespotkanietrumpputinwanchoragewielkieoczekiwaniabrakprzelomu";
import Articlestatusuchodzcowzukrainywpolscepodznakiemzapytania from "@/articles/Articlestatusuchodzcowzukrainywpolscepodznakiemzapytania";
import Articletragediawdziwnowku16latekzaginawbatykumimoczerwonejflagi from "@/articles/Articletragediawdziwnowku16latekzaginawbatykumimoczerwonejflagi";
import Articletragediawstegnieojciecutonalratujaccorki from "@/articles/Articletragediawstegnieojciecutonalratujaccorki";
import Articletragicznetrzesienieziemiwafganistaniesetkiofiaritysiacerannych from "@/articles/Articletragicznetrzesienieziemiwafganistaniesetkiofiaritysiacerannych";
import Articletragicznywypadeknaautostradziea2ciezarowkastanelawogniu from "@/articles/Articletragicznywypadeknaautostradziea2ciezarowkastanelawogniu";
import Articletragicznywypadekwegipciezginelipolscyturysci from "@/articles/Articletragicznywypadekwegipciezginelipolscyturysci";
import Articletragicznywypadekwlizboniezderzenietramwajuzsamochodemsaofiarysmiertelne from "@/articles/Articletragicznywypadekwlizboniezderzenietramwajuzsamochodemsaofiarysmiertelne";
import Articletrzesieniezieminadolnymslaskupolkowiceobudziwstrzaso312 from "@/articles/Articletrzesieniezieminadolnymslaskupolkowiceobudziwstrzaso312";
import Articletrzyniedzwiedziedoodstrzauochronaludziczyskandalekologiczny from "@/articles/Articletrzyniedzwiedziedoodstrzauochronaludziczyskandalekologiczny";
import Articletyrolskieograniczeniamogasparalizowactransportprzezalpy from "@/articles/Articletyrolskieograniczeniamogasparalizowactransportprzezalpy";
import Articleuczenwrekachsluzbnastolatekzukrainyzwerbowanyprzezrosje from "@/articles/Articleuczenwrekachsluzbnastolatekzukrainyzwerbowanyprzezrosje";
import Articleuedziekujepolscezaochronewschodniejgranicy from "@/articles/Articleuedziekujepolscezaochronewschodniejgranicy";
import Articleukraincyratujapolskirynekpracyfitchostrzegaprzedrosnacymdeficytem from "@/articles/Articleukraincyratujapolskirynekpracyfitchostrzegaprzedrosnacymdeficytem";
import Articleukrainskiobywateloskarzonyoprobezamachupaczkabombawpolsce from "@/articles/Articleukrainskiobywateloskarzonyoprobezamachupaczkabombawpolsce";
import Articleukrainskiwkazdejszkolerzadanalizujekontrowersyjnyprojektustawy from "@/articles/Articleukrainskiwkazdejszkolerzadanalizujekontrowersyjnyprojektustawy";
import Articleusykvsduboisiidziswieczoremwalkaoczterypasywagiciezkiej from "@/articles/Articleusykvsduboisiidziswieczoremwalkaoczterypasywagiciezkiej";
import Articleusykznokautowaduboisawembleywidziaodominacje from "@/articles/Articleusykznokautowaduboisawembleywidziaodominacje";
import Articlewaldemarzureknowymfaworytemdotekiministrasprawiedliwosci from "@/articles/Articlewaldemarzureknowymfaworytemdotekiministrasprawiedliwosci";
import Articlewislanarekordowoniskimpoziomiehistoryczneostrzezeniedlapolski from "@/articles/Articlewislanarekordowoniskimpoziomiehistoryczneostrzezeniedlapolski";
import Articlewroclawnaliscienajpiekniejszychmiasteuropy from "@/articles/Articlewroclawnaliscienajpiekniejszychmiasteuropy";
import Articlewroclawwalczyzkomaramiprzyuzyciudronowpierwszetakierozwiazaniewpolsce from "@/articles/Articlewroclawwalczyzkomaramiprzyuzyciudronowpierwszetakierozwiazaniewpolsce";
import Articlewystawaourboyswgdanskuwywolalapolitycznaburze from "@/articles/Articlewystawaourboyswgdanskuwywolalapolitycznaburze";
import Articlezarzutdlarobertabakiewiczazniewazeniesluzbnamosciewslubicach from "@/articles/Articlezarzutdlarobertabakiewiczazniewazeniesluzbnamosciewslubicach";
import Articlezolnierzrannyprzygranicyzbialorusianapietasytuacjawrejonieczeremchy from "@/articles/Articlezolnierzrannyprzygranicyzbialorusianapietasytuacjawrejonieczeremchy";

export const ARTICLE_COMPONENTS = {
  "Article100tysiecyludzinamosciewsydneyogromnyprotestwsprawiegazy": Article100tysiecyludzinamosciewsydneyogromnyprotestwsprawiegazy,
  "Article15sierpniaajedzeniemiesarozwiewamywatpliwosci": Article15sierpniaajedzeniemiesarozwiewamywatpliwosci,
  "Article65miliardadolarowzaczogizkoreiczypolskazbroisienapowaznie": Article65miliardadolarowzaczogizkoreiczypolskazbroisienapowaznie,
  "Article6dnipodlupadrogowkiruszyaogolnoeuropejskaakcjaroadpol": Article6dnipodlupadrogowkiruszyaogolnoeuropejskaakcjaroadpol,
  "Article800tylkodlawybranychwyciekpropozycjireformyoburzyopiniepubliczna": Article800tylkodlawybranychwyciekpropozycjireformyoburzyopiniepubliczna,
  "Article80latpohiroszimieswiatznowigrazogniematomu": Article80latpohiroszimieswiatznowigrazogniematomu,
  "Articleaiwlodowceinabiurkuprzyszloscwlasniesiezaczela": Articleaiwlodowceinabiurkuprzyszloscwlasniesiezaczela,
  "Articlealkoholowaplagaczypolskatracikontrolenadnarodowymnalogiem": Articlealkoholowaplagaczypolskatracikontrolenadnarodowymnalogiem,
  "Articleandrzejdudaodebraodznaczeniejolancielangepowodwspopracazsb": Articleandrzejdudaodebraodznaczeniejolancielangepowodwspopracazsb,
  "Articleautonomicznataksowkabaiduwpadadowykopuwchongqingupowaznepytaniaobezpieczenstwoai": Articleautonomicznataksowkabaiduwpadadowykopuwchongqingupowaznepytaniaobezpieczenstwoai,
  "Articlebronwrekachobywatelicooznaczalawinowywzrostpozwolennabronwpolsce": Articlebronwrekachobywatelicooznaczalawinowywzrostpozwolennabronwpolsce,
  "Articlebryanadamszgwiazdawkrakowietumyfanowiwyprzedanykoncert": Articlebryanadamszgwiazdawkrakowietumyfanowiwyprzedanykoncert,
  "Articleburzeparalizujapolskeimgwostrzegaawarszawatonie": Articleburzeparalizujapolskeimgwostrzegaawarszawatonie,
  "Articlechopinasonatainparispolskasuperprodukcjaolegendziemuzyki": Articlechopinasonatainparispolskasuperprodukcjaolegendziemuzyki,
  "Articlecoldplayikorporacyjnaburzakamerauchwyciaceoiszefowahr": Articlecoldplayikorporacyjnaburzakamerauchwyciaceoiszefowahr,
  "Articlecorazwiekszezmeczeniewojnanaukrainie": Articlecorazwiekszezmeczeniewojnanaukrainie,
  "Articleczydzisjestniedzielahandlowasprawdz31sierpnia2025": Articleczydzisjestniedzielahandlowasprawdz31sierpnia2025,
  "Articleczypolacysagotowinazyciebezalkoholu": Articleczypolacysagotowinazyciebezalkoholu,
  "Articledemolkawizbieprzyjecwsosnowcu36latekwtargnadoszpitalaizdewastowawnetrze": Articledemolkawizbieprzyjecwsosnowcu36latekwtargnadoszpitalaizdewastowawnetrze,
  "Articledramatwkirgistaniepacjenciumierajaprzezbraklekow": Articledramatwkirgistaniepacjenciumierajaprzezbraklekow,
  "Articledziakatonowemieszkaniepolacyzmieniajastylzycianazielony": Articledziakatonowemieszkaniepolacyzmieniajastylzycianazielony,
  "Articleeksplozjadronanawschodziepolskirosnacenapieciaprzygranicy": Articleeksplozjadronanawschodziepolskirosnacenapieciaprzygranicy,
  "Articlefimendurovintagetrophy2025klasycznemotocyklewracajanaszlakipiekoszowa": Articlefimendurovintagetrophy2025klasycznemotocyklewracajanaszlakipiekoszowa,
  "Articlegpt5bezrewolucjiczysztucznainteligencjautknelawmiejscu": Articlegpt5bezrewolucjiczysztucznainteligencjautknelawmiejscu,
  "Articlegrozneburzeiupanadpolskaimgwostrzeganiemalpoowekraju": Articlegrozneburzeiupanadpolskaimgwostrzeganiemalpoowekraju,
  "Articlehamaspublikujenagraniezakadnikaprzerazajacewideoporuszaswiat": Articlehamaspublikujenagraniezakadnikaprzerazajacewideoporuszaswiat,
  "Articleholandiawysylazolnierzyisystempatriotdopolskisolidarnoscnatowpraktyce": Articleholandiawysylazolnierzyisystempatriotdopolskisolidarnoscnatowpraktyce,
  "Articleinflacjaspadaalecenywsklepachwciazwysokiegdzietkwiproblem": Articleinflacjaspadaalecenywsklepachwciazwysokiegdzietkwiproblem,
  "Articleinpostpodostrzaemrekordowypodatekekspansjawhiszpaniiibuntkurierow": Articleinpostpodostrzaemrekordowypodatekekspansjawhiszpaniiibuntkurierow,
  "Articleintelrezygnujezinwestycjiwpolscecodalejzrynkiempoprzewodnikow": Articleintelrezygnujezinwestycjiwpolscecodalejzrynkiempoprzewodnikow,
  "Articlejackowskiprzewidujepozarifaleuchodzcowwpolsce": Articlejackowskiprzewidujepozarifaleuchodzcowwpolsce,
  "Articlejanurbannowymselekcjoneremreprezentacjipolski": Articlejanurbannowymselekcjoneremreprezentacjipolski,
  "Articlejosemnetoperekmezczyznarozebrasienadachurestauracjihelniezapomnitejnocy": Articlejosemnetoperekmezczyznarozebrasienadachurestauracjihelniezapomnitejnocy,
  "Articlekatastrofaf16wradomiuairshow2025przerwanepotragicznymwypadku": Articlekatastrofaf16wradomiuairshow2025przerwanepotragicznymwypadku,
  "Articlekatowickakwkwieczorekzmieniasiewnowoczesnyhubtechnologiczny": Articlekatowickakwkwieczorekzmieniasiewnowoczesnyhubtechnologiczny,
  "Articlekosiniakkamyszwolynwarunkiemakcesjiukrainydoue": Articlekosiniakkamyszwolynwarunkiemakcesjiukrainydoue,
  "Articlekosiniakkamyszzelenskipowiniendolaczycdoszczytutrumpputin": Articlekosiniakkamyszzelenskipowiniendolaczycdoszczytutrumpputin,
  "Articlekrwawyksiezycjuz7wrzesniajednoznajdluzszychzacmienwostatnichlatach": Articlekrwawyksiezycjuz7wrzesniajednoznajdluzszychzacmienwostatnichlatach,
  "Articlelauradahlmeierciezkorannapowypadkuwpakistaniedramatycznaakcjaratunkowawkarakorum": Articlelauradahlmeierciezkorannapowypadkuwpakistaniedramatycznaakcjaratunkowawkarakorum,
  "Articlelauradahlmeierniezyjetragicznyfinawyprawywkarakorum": Articlelauradahlmeierniezyjetragicznyfinawyprawywkarakorum,
  "Articlemanewryzapad2025ukrainaostrzegaprzedprowokacjami": Articlemanewryzapad2025ukrainaostrzegaprzedprowokacjami,
  "Articlemarkcarneywpolscekanadyjskipremierzaciesniastrategicznewiezi": Articlemarkcarneywpolscekanadyjskipremierzaciesniastrategicznewiezi,
  "Articlemasowyatakrosjinaukrainepolskawstanieczujnosci": Articlemasowyatakrosjinaukrainepolskawstanieczujnosci,
  "Articlemasowystopdrivedlacitroenowkierowcybezautserwisysparalizowane": Articlemasowystopdrivedlacitroenowkierowcybezautserwisysparalizowane,
  "Articlemauritiuspodwodaostrzezenieprzedsilnymifalaminawybrzezu": Articlemauritiuspodwodaostrzezenieprzedsilnymifalaminawybrzezu,
  "Articlemcdonaldspolskaukaranyrekordowagrzywna4mlnzawyciekdanychpracownikow": Articlemcdonaldspolskaukaranyrekordowagrzywna4mlnzawyciekdanychpracownikow,
  "Articlemojpiespijewodezkranuhitczyobciachweterynarzepodzieleni": Articlemojpiespijewodezkranuhitczyobciachweterynarzepodzieleni,
  "Articlenowatablicaalimentacyjnaojcieczdwojkadziecizostajezniewielkaczesciapensji": Articlenowatablicaalimentacyjnaojcieczdwojkadziecizostajezniewielkaczesciapensji,
  "Articleobowiazkowebadaniapsychologicznedlakierowcowco5latbezpieczenstwoczyprzesada": Articleobowiazkowebadaniapsychologicznedlakierowcowco5latbezpieczenstwoczyprzesada,
  "Articleorlensprzedajepolskapresskonieceksperymentuzpanstwowymwlascicielemmediow": Articleorlensprzedajepolskapresskonieceksperymentuzpanstwowymwlascicielemmediow,
  "Articleozzyosbourneniezyjelegendarockapozegnaasiezfanami": Articleozzyosbourneniezyjelegendarockapozegnaasiezfanami,
  "Articlepacaminimalnaw2026rokurzadujawniapropozycje": Articlepacaminimalnaw2026rokurzadujawniapropozycje,
  "Articlepanikanatomorrowlandscenawogniuewakuacjatysiecyosob": Articlepanikanatomorrowlandscenawogniuewakuacjatysiecyosob,
  "Articlepierwszakobietakapitanwpolskiejsluzbiesar": Articlepierwszakobietakapitanwpolskiejsluzbiesar,
  "Articlepolacyuciekajanaworkationpracazdalnaiurlopwjednym": Articlepolacyuciekajanaworkationpracazdalnaiurlopwjednym,
  "Articlepolakzatrzymanynabialorusipodzarzutemszpiegostwa": Articlepolakzatrzymanynabialorusipodzarzutemszpiegostwa,
  "Articlepolitycznyklinczprzedzaprzysiezeniemnawrockikontratusk": Articlepolitycznyklinczprzedzaprzysiezeniemnawrockikontratusk,
  "Articlepolskajasnostawiagranicewsparciedlaukrainytakalebezpolskichzolnierzy": Articlepolskajasnostawiagranicewsparciedlaukrainytakalebezpolskichzolnierzy,
  "Articlepolskakupujerekordoweiloscizlotaswiatowyliderw2025roku": Articlepolskakupujerekordoweiloscizlotaswiatowyliderw2025roku,
  "Articlepolskamodernizujeflotef16kontraktwart38mldusd": Articlepolskamodernizujeflotef16kontraktwart38mldusd,
  "Articlepolskarozwazaprzywroceniewizdlaukraincowpowrotgranicczykoniecznosc": Articlepolskarozwazaprzywroceniewizdlaukraincowpowrotgranicczykoniecznosc,
  "Articlepolskastawianaenergetykewiatrowanabaltykumiliardoweinwestycjeiambitnecele": Articlepolskastawianaenergetykewiatrowanabaltykumiliardoweinwestycjeiambitnecele,
  "Articlepolskastawianawlasnyprzemyslamunicji": Articlepolskastawianawlasnyprzemyslamunicji,
  "Articlepolskawstrzymaaschengencosiedziejenagranicachzniemcamiilitwa": Articlepolskawstrzymaaschengencosiedziejenagranicachzniemcamiilitwa,
  "Articlepolskazbozemstoistabilnezbioryalewyzwaniarosna": Articlepolskazbozemstoistabilnezbioryalewyzwaniarosna,
  "Articlepolskazmedalaminaigrzyskachswiatowych2025imponujacydorobekwchinach": Articlepolskazmedalaminaigrzyskachswiatowych2025imponujacydorobekwchinach,
  "Articlepolskiastronautasawoszuznanskibezpieczniewrocinaziemie": Articlepolskiastronautasawoszuznanskibezpieczniewrocinaziemie,
  "Articlepolskoirlandzkaakcjarozbijaganginarkotykowewarte240mln": Articlepolskoirlandzkaakcjarozbijaganginarkotykowewarte240mln,
  "Articleprezydentdudawogniukrytykipowypowiedzionato": Articleprezydentdudawogniukrytykipowypowiedzionato,
  "Articleprezydentnawrockizawetowaltrzyustawynajwiekszykryzyslegislacyjnykadencji": Articleprezydentnawrockizawetowaltrzyustawynajwiekszykryzyslegislacyjnykadencji,
  "Articleprezydentpodnosiwiekemerytalnypodpiszozony": Articleprezydentpodnosiwiekemerytalnypodpiszozony,
  "Articleprezydentpolskizadareparacjiodniemiecwrocznicewybuchuiiwojnyswiatowej": Articleprezydentpolskizadareparacjiodniemiecwrocznicewybuchuiiwojnyswiatowej,
  "Articleprokuraturazlecasekcjezwlokstanislawasoyki": Articleprokuraturazlecasekcjezwlokstanislawasoyki,
  "Articlerocznicapakturibbentropmolotowostrzezenieprezydentanawrockiego": Articlerocznicapakturibbentropmolotowostrzezenieprezydentanawrockiego,
  "Articlerosyjskinalotnakijowofiaryizniszczeniawstolicyukrainy": Articlerosyjskinalotnakijowofiaryizniszczeniawstolicyukrainy,
  "Articlerzadkiezjawiskonadbaltykiemazosiemtrabwodnychjednoczesnie": Articlerzadkiezjawiskonadbaltykiemazosiemtrabwodnychjednoczesnie,
  "Articlerzadpodnosipodatekdlabankowdodatkowe65mldzlnaobrone": Articlerzadpodnosipodatekdlabankowdodatkowe65mldzlnaobrone,
  "Articlerzadrezygnujezpodatkuodrezerwbankowych": Articlerzadrezygnujezpodatkuodrezerwbankowych,
  "Articlesensacyjneodkryciewgdanskugrobrycerzapodlodziarnia": Articlesensacyjneodkryciewgdanskugrobrycerzapodlodziarnia,
  "Articlesiniceatakujabatykplazezamknietegisbijenaalarm": Articlesiniceatakujabatykplazezamknietegisbijenaalarm,
  "Articlesmiercpodczaspolowanianalubelszczyznietragediawlesie": Articlesmiercpodczaspolowanianalubelszczyznietragediawlesie,
  "Articlespotkanietrumpputinwanchoragewielkieoczekiwaniabrakprzelomu": Articlespotkanietrumpputinwanchoragewielkieoczekiwaniabrakprzelomu,
  "Articlestatusuchodzcowzukrainywpolscepodznakiemzapytania": Articlestatusuchodzcowzukrainywpolscepodznakiemzapytania,
  "Articletragediawdziwnowku16latekzaginawbatykumimoczerwonejflagi": Articletragediawdziwnowku16latekzaginawbatykumimoczerwonejflagi,
  "Articletragediawstegnieojciecutonalratujaccorki": Articletragediawstegnieojciecutonalratujaccorki,
  "Articletragicznetrzesienieziemiwafganistaniesetkiofiaritysiacerannych": Articletragicznetrzesienieziemiwafganistaniesetkiofiaritysiacerannych,
  "Articletragicznywypadeknaautostradziea2ciezarowkastanelawogniu": Articletragicznywypadeknaautostradziea2ciezarowkastanelawogniu,
  "Articletragicznywypadekwegipciezginelipolscyturysci": Articletragicznywypadekwegipciezginelipolscyturysci,
  "Articletragicznywypadekwlizboniezderzenietramwajuzsamochodemsaofiarysmiertelne": Articletragicznywypadekwlizboniezderzenietramwajuzsamochodemsaofiarysmiertelne,
  "Articletrzesieniezieminadolnymslaskupolkowiceobudziwstrzaso312": Articletrzesieniezieminadolnymslaskupolkowiceobudziwstrzaso312,
  "Articletrzyniedzwiedziedoodstrzauochronaludziczyskandalekologiczny": Articletrzyniedzwiedziedoodstrzauochronaludziczyskandalekologiczny,
  "Articletyrolskieograniczeniamogasparalizowactransportprzezalpy": Articletyrolskieograniczeniamogasparalizowactransportprzezalpy,
  "Articleuczenwrekachsluzbnastolatekzukrainyzwerbowanyprzezrosje": Articleuczenwrekachsluzbnastolatekzukrainyzwerbowanyprzezrosje,
  "Articleuedziekujepolscezaochronewschodniejgranicy": Articleuedziekujepolscezaochronewschodniejgranicy,
  "Articleukraincyratujapolskirynekpracyfitchostrzegaprzedrosnacymdeficytem": Articleukraincyratujapolskirynekpracyfitchostrzegaprzedrosnacymdeficytem,
  "Articleukrainskiobywateloskarzonyoprobezamachupaczkabombawpolsce": Articleukrainskiobywateloskarzonyoprobezamachupaczkabombawpolsce,
  "Articleukrainskiwkazdejszkolerzadanalizujekontrowersyjnyprojektustawy": Articleukrainskiwkazdejszkolerzadanalizujekontrowersyjnyprojektustawy,
  "Articleusykvsduboisiidziswieczoremwalkaoczterypasywagiciezkiej": Articleusykvsduboisiidziswieczoremwalkaoczterypasywagiciezkiej,
  "Articleusykznokautowaduboisawembleywidziaodominacje": Articleusykznokautowaduboisawembleywidziaodominacje,
  "Articlewaldemarzureknowymfaworytemdotekiministrasprawiedliwosci": Articlewaldemarzureknowymfaworytemdotekiministrasprawiedliwosci,
  "Articlewislanarekordowoniskimpoziomiehistoryczneostrzezeniedlapolski": Articlewislanarekordowoniskimpoziomiehistoryczneostrzezeniedlapolski,
  "Articlewroclawnaliscienajpiekniejszychmiasteuropy": Articlewroclawnaliscienajpiekniejszychmiasteuropy,
  "Articlewroclawwalczyzkomaramiprzyuzyciudronowpierwszetakierozwiazaniewpolsce": Articlewroclawwalczyzkomaramiprzyuzyciudronowpierwszetakierozwiazaniewpolsce,
  "Articlewystawaourboyswgdanskuwywolalapolitycznaburze": Articlewystawaourboyswgdanskuwywolalapolitycznaburze,
  "Articlezarzutdlarobertabakiewiczazniewazeniesluzbnamosciewslubicach": Articlezarzutdlarobertabakiewiczazniewazeniesluzbnamosciewslubicach,
  "Articlezolnierzrannyprzygranicyzbialorusianapietasytuacjawrejonieczeremchy": Articlezolnierzrannyprzygranicyzbialorusianapietasytuacjawrejonieczeremchy,
};
